modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
issueTrackerURL = "${mod_issuepage}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
#provides = [ "tclayer", "cclayer" ]
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}, ${mod_contributors}"
credits = "${mod_credits}"
description = '''
${mod_description}
'''
logoFile = "assets/${mod_id}/icon.png"
displayURL = "${mod_sourcepage}"

[[mods]]
modId = "tclayer"
version = "${mod_version}"

[[mods]]
modId = "cclayer"
version = "${mod_version}"

[[mixins]]
config = '${mod_id}-common.mixins.json'
[[mixins]]
config = '${mod_id}-neoforge.mixins.json'
[[mixins]]
config = '${mod_id}-trinkets.mixins.json'
[[mixins]]
config = '${mod_id}-curios.mixins.json'

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${neoforge_minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "owo"
type = "required"
versionRange = "${owo_neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "accessories"
type = "required"
versionRange = "${accessories_neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "curios"
type = "optional"
versionRange = "${curios_suggets_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "curios"
type = "incompatible"
versionRange = "${curios_breaks_version_range}"
ordering = "NONE"
side = "BOTH"

#[[dependencies.${mod_id}]]
#modId = "cclayer"
#type = "incompatible"
#versionRange = ""
#ordering = "NONE"
#side = "BOTH"
